---

name: Javascript

"on":
  push:
    branches:
      - develop
      - main
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-pre[0-9]+"
  pull_request:
    branches:
      - develop
      - main
      - master
    paths:
      - "grpc/clients/js/**"

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: |
          cd grpc/clients/js
          npm ci

      - name: Lint
        run: |
          cd grpc/clients/js
          npm run lint

      - name: Test
        env:
          CI: true
          GRPC_NODE: ${{ secrets.GRPC_NODE }}
          WALLETSERVER: ${{ secrets.WALLETSERVER }}
        run: |
          cd grpc/clients/js
          npm test

      - name: Push release to npm (public)
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.node-version == '14.x' }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd grpc/clients/js
          npm publish --access public .
